apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: fminzoni/go-docker-simpleapp
        name: web
        env:
        - name: DATABASE_PORT_27017_TCP_ADDR
          value: mongo
          name: DB_NAME
          value: TEST
        ports:
        - containerPort: 8080
          name: http-server
